version: '2'
services:
    teamspeak:
        build: .
        command: /start
        ports:
          - "9987/udp"
          - "30033"
          - "10011"
        volumes:
            - /data
        restart: always
